### PR TITLE
add aditional analysis output

### PR DESCRIPTION
**Pull request by flovo**
I added some more outputs to `TallyGameAnalytics`.

1) I added some bot accounts to `players_to_inspect.ini`. Especially the rating of DDK bots varies strongly over time. 
2) I added columns for min and max rating and deviation to the Inspected users list. This columns take the ratings and deviations of the last month (28 days) of the player. This should give an impression of how much the ratings are varying over time.
    ```
    Inspected users from ../analysis/players_to_inspect.ini
               anoek    17k     1326.81 +-  65.68 (0.060018)     1327  1327      66   66
            Uberdude     8d     2811.91 +-  78.27 (0.059924)     2807  2839      78   78
                 nrx     4k     1965.12 +-  68.94 (0.060052)     1965  2261      68   70
            Sadaharu     5d     2568.08 +-  83.96 (0.060073)     2561  2605      79   84
               GnuGo     9k     1680.39 +-  80.08 (0.090721)     1666  1680      80   80
            mark5000     2d     2303.76 +-  74.00 (0.060142)     2282  2319      72   75
               xhu98     2d     2362.52 +-  77.22 (0.060126)     2334  2422      75   78
          RoyalLeela     3d     2440.06 +-  70.94 (0.060454)     2440  2471      70   71
               flovo    16k     1366.88 +-  64.44 (0.060026)     1367  1384      64   65
       Master Mantis    11k     1569.46 +-  72.67 (0.070041)     1569  1569      73   73
     amybot-beginner    27k      948.62 +- 101.86 (0.149572)      643  1369      95  125
          amybot-ddk    18k     1278.53 +-  70.43 (0.076326)     1133  1522      68   78
    ```
    You can see the rating of the amybots variing by ~400 points in one month. 
3) I added a completly new output line, showing the script name, blacks win chance on 19x19 for 0, 1, and 2 handicap, the prediction accuracity (how often did the stronger player win) and a column showing how often the rating changed in the wrong direction (down after a win or vice verca). 
    This line is formated as markdown table, so we can create somewhere a table, showing some key figures for the various algorithms.
    ```
    | Algorithm name | Black wins h0 | h1 | h2 | Stronger wins | rating changed in the wrong direction |
    |:---------------|--------------:|---:|---:|--------------:|---------------------------------------:
    | analyze_glicko2_daily_windows.py | 45.5% | 42.4% | 41.5% | 53.2% | 12.1085% |
    ```

| Algorithm name | Black wins h0 | h1 | h2 | Stronger wins | rating changed in the wrong direction |
|:---------------|--------------:|---:|---:|--------------:|---------------------------------------:
| analyze_glicko2_daily_windows.py | 45.5% | 42.4% | 41.5% | 53.2% | 12.1085% |
| analyze_glicko2_one_game_at_a_time.py | 49.6% | 43.1% | 42.2% | 53.9% |  0.0000% |

### CODE REVIEW

**Comment by flovo** [comment]
To measure the quality by how often black wins is flawed for multiple reasons. 
1) When ratings relative to each other change, some games are excluded from the benchmark and some others included. If the pairings are not evenly distributed (and they aren't) the number of games (and the rating distribution) might change significantly. This is especially a problem for handicap games, for which the rank variance is 1 rank for most games.
2) Colour Auto assigned black to the weaker player (if the rank difference is > 1). Since Auto is the default, we should expect a bias for black loosing more games than white.

Measuring the quality of a rating algorithm by comparing the predicted outcome (higher ranked player should win) to the actual outcome is the usual benchmark when comparing rating algorithms. An algorithm is expected to perform better if it predicts the outcome of a game right in more cases than another algorithm.

**Comment by flovo** [comment]
I added a rank-handicap table showing the prediction quality to the output and removed the black wins stats from the short stats output.

```
  12.937.409 /   12.938.342 games processed.    0.0s remaining
12.938.342 games processed in 538.0 seconds

9x9:   1069734 games
           hc 0     hc 1     hc 2     hc 3     hc 4     hc 5     hc 6     hc 7     hc 8     hc 9   
30k-26k   46.7%    40.8%    50.3%    69.4%    81.5%    80.1%    82.7%    77.8%    80.0%    73.4%   
25k-21k   45.9%    44.4%    49.8%    65.9%    71.6%    67.6%    81.4%    93.3%    75.0%    55.6%   
20k-16k   45.7%    43.3%    46.5%    56.1%    72.5%    57.1%    79.2%   100.0%    75.0%    30.3%   
15k-11k   46.5%    42.3%    49.9%    62.4%    81.6%    33.3%    83.3%     0.0%   100.0%     0.0%   
10k- 6k   49.1%    49.3%    68.6%    75.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%   
 5k- 1k   50.7%   100.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%   
 1d- 5d   66.7%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%   

13x13:   394049 games
           hc 0     hc 1     hc 2     hc 3     hc 4     hc 5     hc 6     hc 7     hc 8     hc 9   
30k-26k   43.4%    44.1%    43.8%    33.3%    46.0%    65.1%    59.2%    64.3%   100.0%    61.9%   
25k-21k   43.0%    45.9%    44.8%    35.8%    43.2%    47.3%    30.2%    43.2%    60.0%    55.4%   
20k-16k   43.7%    45.8%    46.4%    31.9%    35.3%    54.8%    45.7%    42.9%    80.0%    36.8%   
15k-11k   45.3%    46.4%    48.8%    37.2%    43.6%    43.8%    40.0%   100.0%     0.0%    33.3%   
10k- 6k   49.3%    46.6%    36.5%    63.6%   100.0%     0.0%     0.0%     0.0%     0.0%     0.0%   
 5k- 1k   53.5%    60.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%   
 1d- 5d    0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%   

19x19:   1689998 games
           hc 0     hc 1     hc 2     hc 3     hc 4     hc 5     hc 6     hc 7     hc 8     hc 9   
30k-26k   44.1%    38.9%    37.7%    37.5%    38.8%    36.2%    32.3%    32.9%    29.2%    24.2%   
25k-21k   44.7%    40.7%    38.9%    40.4%    42.7%    40.2%    41.6%    35.1%    33.8%    26.2%   
20k-16k   44.8%    41.8%    40.7%    40.1%    41.3%    37.8%    36.5%    35.7%    34.1%    37.7%   
15k-11k   45.8%    43.2%    43.0%    42.0%    41.2%    39.9%    42.4%    44.4%    45.0%    42.0%   
10k- 6k   45.9%    42.4%    41.8%    39.5%    41.0%    42.5%    40.6%    37.7%    31.7%    22.9%   
 5k- 1k   44.6%    44.3%    42.9%    47.7%    39.1%    36.0%    14.3%     0.0%     0.0%     0.0%   
 1d- 5d   55.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%   

Overall:   3153781 games
           hc 0     hc 1     hc 2     hc 3     hc 4     hc 5     hc 6     hc 7     hc 8     hc 9   
30k-26k   45.9%    41.6%    43.1%    45.3%    52.3%    52.2%    42.4%    37.3%    32.6%    48.2%   
25k-21k   45.2%    44.2%    41.6%    42.0%    44.7%    41.9%    42.2%    37.3%    34.5%    33.3%   
20k-16k   45.1%    43.4%    42.4%    39.7%    41.9%    38.2%    36.8%    35.8%    34.4%    37.4%   
15k-11k   45.9%    43.4%    43.8%    42.1%    41.5%    39.9%    42.5%    44.4%    45.1%    41.7%   
10k- 6k   46.2%    42.5%    42.0%    39.8%    41.0%    42.4%    40.6%    37.7%    31.7%    22.5%   
 5k- 1k   45.4%    44.5%    42.9%    47.7%    39.1%    36.0%    14.3%     0.0%     0.0%     0.0%   
 1d- 5d   56.5%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%   

How often does the player with the higher rating win.

9x9:   1069734 games
           hc 0     hc 1     hc 2     hc 3     hc 4     hc 5     hc 6     hc 7     hc 8     hc 9   
30k-26k   51.3%    51.9%    52.8%    54.0%    57.4%    57.1%    67.3%    72.2%    80.0%    57.0%   
25k-21k   52.0%    51.6%    50.7%    55.0%    51.4%    50.5%    60.5%    55.6%   100.0%    52.8%   
20k-16k   52.8%    51.7%    52.0%    54.5%    50.7%    56.0%    66.7%    75.0%    75.0%    54.5%   
15k-11k   52.6%    51.7%    51.6%    53.6%    63.2%    55.6%    16.7%     0.0%   100.0%     0.0%   
10k- 6k   53.2%    47.4%    57.1%    75.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%   
 5k- 1k   49.4%   100.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%   
 1d- 5d   33.3%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%   

13x13:   394049 games
           hc 0     hc 1     hc 2     hc 3     hc 4     hc 5     hc 6     hc 7     hc 8     hc 9   
30k-26k   52.1%    51.7%    49.7%    56.1%    49.3%    55.4%    49.0%    21.4%    33.3%    47.6%   
25k-21k   52.5%    51.5%    53.5%    56.3%    51.1%    52.7%    48.8%    45.9%    53.3%    47.7%   
20k-16k   53.4%    52.6%    52.0%    56.2%    52.1%    51.6%    65.7%    42.9%    80.0%    31.6%   
15k-11k   53.2%    51.4%    49.5%    51.9%    51.8%    56.2%    40.0%   100.0%     0.0%    66.7%   
10k- 6k   53.1%    49.4%    56.8%    57.6%     0.0%    50.0%     0.0%     0.0%     0.0%    50.0%   
 5k- 1k   54.2%    40.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%   
 1d- 5d    0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%   

19x19:   1689998 games
           hc 0     hc 1     hc 2     hc 3     hc 4     hc 5     hc 6     hc 7     hc 8     hc 9   
30k-26k   51.4%    53.9%    52.1%    51.3%    54.7%    54.0%    52.8%    52.0%    53.0%    58.9%   
25k-21k   52.8%    51.7%    52.1%    51.7%    52.8%    52.4%    49.7%    52.3%    50.3%    49.7%   
20k-16k   53.2%    52.1%    52.1%    51.6%    52.1%    48.6%    48.0%    48.5%    43.6%    50.6%   
15k-11k   53.3%    51.9%    51.0%    50.8%    50.8%    49.8%    49.5%    48.6%    48.8%    53.6%   
10k- 6k   53.3%    50.4%    50.6%    50.4%    51.2%    51.6%    50.6%    52.0%    43.0%    45.0%   
 5k- 1k   53.7%    52.8%    52.4%    48.5%    46.9%    60.0%    28.6%     0.0%     0.0%     0.0%   
 1d- 5d   50.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%   

Overall:   3153781 games
           hc 0     hc 1     hc 2     hc 3     hc 4     hc 5     hc 6     hc 7     hc 8     hc 9   
30k-26k   51.4%    51.9%    51.8%    53.4%    54.4%    55.1%    54.2%    51.8%    54.0%    56.9%   
25k-21k   52.3%    51.6%    52.1%    53.1%    52.5%    52.3%    49.9%    52.2%    50.6%    49.8%   
20k-16k   53.0%    52.0%    52.0%    52.4%    52.0%    48.7%    48.2%    48.5%    43.8%    50.3%   
15k-11k   53.1%    51.8%    50.9%    50.9%    50.8%    49.8%    49.4%    48.6%    48.8%    53.4%   
10k- 6k   53.3%    50.4%    50.7%    50.5%    51.1%    51.6%    50.6%    52.0%    43.0%    45.1%   
 5k- 1k   53.3%    52.8%    52.4%    48.5%    46.9%    60.0%    28.6%     0.0%     0.0%     0.0%   
 1d- 5d   47.8%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%   

Inspected users from analysis/players_to_inspect.ini
               anoek    18k     1270.35 +-  62.78 (0.060003)     1270  1270      63   63
            Uberdude     4d     2451.82 +-  63.71 (0.060040)     2452  2490      63   64
                 nrx     7k     1823.95 +-  43.08 (0.060690)     1797  1922      42   57
            Sadaharu     5k     1916.03 +-  64.88 (0.062026)     1916  1988      60   65
               GnuGo    16k     1352.94 +-  51.98 (0.149916)     1353  1361      52   52
            mark5000     8k     1755.62 +-  60.12 (0.060674)     1742  1779      59   61
               xhu98     8k     1753.83 +-  60.74 (0.061965)     1717  1851      61   68
          RoyalLeela     7k     1784.62 +-  98.35 (0.149969)     1785  1826      95   98
               flovo    19k     1214.43 +-  61.87 (0.061063)     1214  1229      62   62
       Master Mantis    21k     1163.98 +-  35.78 (0.149058)     1164  1164      36   36
     amybot-beginner    28k      935.53 +-  15.92 (0.150000)      652  1055      12   33
          amybot-ddk    24k     1034.36 +-  23.41 (0.143584)      669  1139      16   56


| Algorithm name | Stronger wins | h0 | h1 | h2 | rating changed in the wrong direction |
|:---------------|--------------:|---:|---:|--------------:|---------------------------------------:
| analyze_glicko2_daily_windows.py | 52.9% | 53.2% | 51.8% | 51.5% | 13.2848% |
```

| Algorithm name | Stronger wins | h0 | h1 | h2 | rating changed in the wrong direction |
|:---------------|--------------:|---:|---:|--------------:|---------------------------------------:
| analyze_glicko2_one_game_at_a_time.py | 54.1% | 53.9% | 55.3% | 54.6% |  0.0000% |
| analyze_glicko2_daily_windows.py | 52.9% | 53.2% | 51.8% | 51.5% | 13.2848% |

**Comment by TokumotoK** [comment]
While considering what flovo wrote above, a question kept on popping up in my mind:

Should bot games be included in the analysis?

1. One bot account does not get used by a single version of a code.
Except for a very few number of accounts like Kugutsu, on which I've kept a single version for years, it is natural to have updates of different strengths applied periodically.
2. Humans always find a way to beat a bot.
I have seen:
 2-1. An user kept on using the same opening and the subsequent sequence (probably with a sequence recorder) , so that he/she would eventually end up with a winning sequence -possibly with the intent to use it over and over.
 2-2. An user starting 2 games at once with a bot, one as White, another as Black.  He then used the bot moves as his own, practically making one of the games a bot self-play.  Note that he could have used different accounts to do the same.
and also:
 2-3. As a bot operator, I could control a bot to adjust my (or somebody else's) rank up or down.

We just can't under-estimate the ingeniousness of human brain, and this is the reason why I have advocated for making all bot games unranked.  And I believe it could be reasons why bot games should be excluded from the analysis of ogs rating system.

**Comment by flovo** [comment]
The whole data are biased to white wins, especially in the case of handicap games.
This makes it hard to get good numbers.

**Comment by TokumotoK** [comment]
"The whole data" is what I am questioning.
In the players_to_inspect list above, only 5 accounts out of 12, anoek/nrx/mark5000/xhu98/flovo, are not bot accounts or someone I suspect as a botter.  I'd think the number of bot games in the whole data is huge, and humans tend to take losing to a bot very lightly.  Do you see the likelihood of bot games biasing the data in more than one way?

**Comment by anoek** [comment]
I'm sorry I totally missed this PR was here, I'll get it patched and merged in the next bit here

**Comment by anoek** [comment]
Thank you @flovo, this includes some good indicators, I'm sorry it took me so long to get it merged, I've been split in a lot of directions recently.

**Pull request merged**
